server:
  port: ${PORT:8080}
management:
  security:
    enabled: false
spring:
  rabbitmq:
    host: ${cloudamqp.credentials.http_api_uri:localhost}
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default-binder: rabbit